//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace udodPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id_o { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> id_f { get; set; }
        public Nullable<int> id_ct { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual food food { get; set; }
    }
}
