//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace udodPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo
    {
        public int id_p { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> procent { get; set; }
    }
}
